# Generated by Django 5.0.4 on 2026-05-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='data',
        ),
    ]
