# Generated by Django 5.0.4 on 2026-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensorreading_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
